version: '2'
services:
  phppgadmin:
    image: chatelao/docker-phppgadmin
    ports:
      - "8089:80"
    links:
      - postgres-osm:pg
  ui-for-docker:
    image: uifd/ui-for-docker
    ports:
     - "8099:9000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  docker-compose-ui:
    restart: always
    image: francescou/docker-compose-ui:0.21.0
#    container_name: docker_compose_ui
#    hostname: docker_compose_ui
    ports:
     - "8095:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
